import type { ExpoConfig } from 'expo/config';

// Prebuild/CNG + dev client (NOT Expo Go) — Rive and native Google Sign-In
// need native modules (docs/phase-0/10 finalized decision). Native projects are
// generated by `expo prebuild` / `expo run:*` and stay gitignored.
const config: ExpoConfig = {
  name: 'Nogoolin',
  slug: 'nogoolin',
  version: '0.1.0',
  scheme: 'nogoolin', // deep link for auth callbacks (nogoolin://auth/callback)
  orientation: 'portrait',
  userInterfaceStyle: 'light',
  newArchEnabled: true,
  ios: {
    bundleIdentifier: 'mn.nogoolin.app',
    supportsTablet: false,
  },
  android: {
    package: 'mn.nogoolin.app',
  },
  plugins: [
    'expo-router',
    // Phase 3: '@rive-app/react-native' config plugin joins here
  ],
  experiments: {
    typedRoutes: true,
  },
};

export default config;
